# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.4.2"

gem 'minitest'
# gem "rails"
group :development do
  gem 'rubocop', require: false
  # rubocop-railsは不要ではないですかね？
  gem 'rubocop-rails', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-packaging', require: false
  gem 'rubocop-minitest', require: false
  gem 'rubocop-md', require: false
end
